//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HosePital.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_PRODUCTTYPE
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public decimal ProductPrice { get; set; }
        public string ProductImg { get; set; }
        public int PTypeID { get; set; }
        public int ProductCount { get; set; }
        public Nullable<int> ProductPut { get; set; }
    
        public virtual db_PTYPE db_PTYPE { get; set; }
    }
}
