//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HosePital.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_INPUT
    {
        public int InID { get; set; }
        public string CustomerName { get; set; }
        public int CTypeID { get; set; }
        public System.DateTime CustomerInDate { get; set; }
        public System.DateTime CustomerOutDate { get; set; }
        public int RoomNID { get; set; }
        public int WorkerID { get; set; }
        public string CustomerIDNumber { get; set; }
        public int CustomerPeoper { get; set; }
        public string CustomerSex { get; set; }
        public Nullable<decimal> CustomerPrice { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerPhone { get; set; }
        public virtual db_CType db_CType { get; set; }
        public virtual db_ROOM db_ROOM { get; set; }
        public virtual db_WORKER db_WORKER { get; set; }
    }
}
