//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HosePital.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_ROOMTYPE
    {
        public db_ROOMTYPE()
        {
            this.db_ROOM = new HashSet<db_ROOM>();
        }
    
        public int RoomID { get; set; }
        public string RoomType { get; set; }
        public decimal RoomPrice { get; set; }
    
        public virtual ICollection<db_ROOM> db_ROOM { get; set; }
    }
}
